### PR TITLE
Changing doc page for ChemicalToolBox.

### PR DESCRIPTION
**Pull request by tnabtaf**
Merged former URL with platform directory entry for ChemicalToolBox.

### CODE REVIEW

**Comment by afgane** [comment]
I am not sure if this repo is used any more. We've migrated to a [Helm chart for deploying CloudLaunch](https://github.com/CloudVE/cloudlaunch-helm) so this repo may be obsolete. @nuwang?

**Comment by tnabtaf** [comment]
Thanks for the pointer to the helm chart.  I missed that one.  WIll submit a PR for that.

**Comment by tnabtaf** [comment]
Submitted.

And if this repo is deprecated / dead, then we should probably say that at the top of the README.

**Comment by nuwang** [comment]
No longer maintained yes. Will add a note and archive.

**Pull request closed without merging**
